### PR TITLE
Add License and Notice

### PR DESCRIPTION
**Pull request by thaJeztah**
ping @salah-khan

### CODE REVIEW

**Review by andrewhsu — APPROVED** [review]
~LGTM~ trigger happy

**Review by andrewhsu — CHANGES_REQUESTED** [review]
needs year in copy right notice https://en.wikipedia.org/wiki/Copyright_notice

**Comment by thaJeztah** [comment]
Updated!

**Review by andrewhsu — APPROVED** [review]
LGTM

**Pull request merged**
